name: Enhancement
description: Request a new feature or improvement.
type: enhancement
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: Thank you for helping RenderPearl improve! Make sure to try the latest version before submitting an issue, as it may have already been solved.

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Explain what you would like to see added to RenderPearl. Feel free to provide images, links, etc. and other information you think may be useful.
          placeholder: RenderPearl should have full translations for Pirate Speak, LOLCAT and Danish.
      validations:
          required: true
