# Sub-Surface Scattering
	#block.0=%minecraft:flowers %minecraft:leaves %minecraft:saplings %minecraft:crops minecraft:short_grass minecraft:tall_grass #banners

# Metal
	block.0=minecraft:ancient_debris minecraft:raw_iron_block minecraft:raw_gold_block minecraft:raw_copper_block minecraft:netherite_block minecraft:gold_block minecraft:iron_block minecraft:copper_block \
	%minecraft:copper %minecraft:copper_chests %minecraft:bars %minecraft:lanterns %minecraft:lightning_rods %minecraft:rails \
	minecraft:copper_door minecraft:exposed_copper_door minecraft:iron_door minecraft:oxidized_copper_door minecraft:waxed_copper_door minecraft:waxed_exposed_copper_door minecraft:waxed_oxidized_copper_door minecraft:waxed_weathered_copper_door minecraft:weathered_copper_door \
	minecraft:copper_trapdoor minecraft:exposed_copper_trapdoor minecraft:iron_trapdoor minecraft:oxidized_copper_trapdoor minecraft:waxed_copper_trapdoor minecraft:waxed_exposed_copper_trapdoor minecraft:waxed_oxidized_copper_trapdoor minecraft:waxed_weathered_copper_trapdoor minecraft:weathered_copper_trapdoor
	#TODO: ^

# Emissive Light Level (1-15)
	block.2=minecraft:repeater:powered=true minecraft:comparator:powered=true
	block.15=minecraft:chorus_flower

	#ifdef EMISSIVE_EMERALD_BLOCK
		block.10=minecraft:emerald_block
	#endif

	#ifdef EMISSIVE_LAPIS_BLOCK
		block.11=minecraft:lapis_block
	#endif

	#ifdef EMISSIVE_REDSTONE_BLOCK
		block.12=minecraft:redstone_block
	#endif
